language: cpp
compiler:
  - clang

jobs:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - g++-multilib
            - lib32z1-dev
            - python3-pip

    - os: osx
      osx_image: xcode9.4

env:
  global:
    - SOURCEMOD_VERSION=1.10-dev
    - TARGET_ARCHS=x86,x86_64

install:
  - git clone https://github.com/alliedmodders/sourcemod.git -b $SOURCEMOD_VERSION --depth 1 -j8 --recurse-submodules --shallow-submodules $TRAVIS_BUILD_DIR/../sourcemod
  - git clone https://github.com/alliedmodders/ambuild.git --depth 1 $TRAVIS_BUILD_DIR/../ambuild
  - python3 -m pip install --upgrade pip setuptools
  - python3 -m pip install $TRAVIS_BUILD_DIR/../ambuild

script:
  - mkdir $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
  - perl ../curl/lib/mk-ca-bundle.pl
  - python3 ../configure.py --enable-optimize --targets=$TARGET_ARCHS
  - ambuild

before_deploy:
  - tar -czf sm-ripext-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz -C package/ addons/

deploy:
  provider: releases
  api_key:
    secure: ZnwybxNCMbb9l+njaP1NxtDWqDwz+n1vba/IoB6dvv5t6HW8XG9ZtbGME9dLF1x8EyH7TUMGFbWLKkbFecxMnhJCOuJ8AZ26iv6tR8R28sK/sfb8DXZXMd/NfBM4sdlQEIncW9EddUho3mWeVFkPWiG8cBb53dGaTCq5khOf0/GdIbTz9ba/G8BL5lOT/2agufDiVM7bVFsgH3iPjPEPxQWV9vH1sU5eT8/0bkEwpBP90EgYdGjhiZcrKQCq94+zJvPWAoPv+IHBX9K3kM0OOEE+aMY2/Xi82pKZhDJ/dgHv6OQ3EWZja/E6NgsropFxfCqqS3JTNt7Qdv9E3Dr7IAz3pq8cmxu6k+0J7z0SjlXaIy1LrqnA6+ttfxDyNaVPUqY2MkS8jKlFlAsTEt6EfO1ViqHXwlU8kaRKiZ8eR0usSLvDrxJomBZTSgrCJySmRjSrjvMhjVQLuiPLRcBKmut0aOM+Vzzww1EXq3kOmU1V6Q8yMay7y0FbTS/SuA7SNbhlNC1HDO+dTcdLTt1uvD/6VkDCuz5Nh0Pe8R87YkqWKoTS6YxvR4Ixih/fVkKvgAqw6seZf+bQ6qw5HsEFx7P9qTMHYYjYHQ7jsdNTnMGpg+NW35J8ApJx7oaCx3IGfzGZHwnWqFbDBMgTL8OfP8vzx47Y/XZj0fRle6dlfvA=
  file: sm-ripext-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz
  skip_cleanup: true
  on:
    tags: true
