version: '{branch}-{build}'

image: Visual Studio 2015

environment:
  SOURCEMOD_VERSION: 1.10-dev

install:
  - '"%VS140COMNTOOLS%vsvars32.bat"'
  - git clone https://github.com/alliedmodders/sourcemod.git -b %SOURCEMOD_VERSION% --depth 1 --recursive %APPVEYOR_BUILD_FOLDER%\..\sourcemod
  - git clone -b 2.1 https://github.com/alliedmodders/ambuild.git --depth 1 %APPVEYOR_BUILD_FOLDER%\..\ambuild
  - cd %APPVEYOR_BUILD_FOLDER%\..\ambuild && python setup.py build && python setup.py install

build_script:
  - mkdir %APPVEYOR_BUILD_FOLDER%\build && cd %APPVEYOR_BUILD_FOLDER%\build
  - perl ..\curl\lib\mk-ca-bundle.pl
  - python ..\configure.py --enable-optimize
  - C:\Python27\Scripts\ambuild

after_build:
  - if /i "%APPVEYOR_REPO_TAG%"=="true" 7z a sm-ripext-%APPVEYOR_REPO_TAG_NAME%-windows.zip .\package\*

artifacts:
  - path: build\sm-ripext-$(appveyor_repo_tag_name)-windows.zip

deploy:
  - provider: GitHub
    auth_token:
      secure: W5NLiQPcN6s71QOYkqmv7UjmHzHI8NFNuPPBnBajdipPN4wl1jt7ecGUpSb9f9nO
    artifact: build\sm-ripext-$(appveyor_repo_tag_name)-windows.zip
    on:
      appveyor_repo_tag: true
