version: '{branch}-{build}'

environment:
  SOURCEMOD_VERSION: 1.8-dev

install:
  - '"%VS120COMNTOOLS%vsvars32.bat"'
  - git clone https://github.com/alliedmodders/sourcemod.git -b %SOURCEMOD_VERSION% --depth 1 --recursive %APPVEYOR_BUILD_FOLDER%\..\sourcemod
  - git clone https://github.com/alliedmodders/ambuild.git --depth 1 %APPVEYOR_BUILD_FOLDER%\..\ambuild
  - cd %APPVEYOR_BUILD_FOLDER%\..\ambuild && python setup.py build && python setup.py install

build_script:
  - mkdir %APPVEYOR_BUILD_FOLDER%\build && cd %APPVEYOR_BUILD_FOLDER%\build
  - python ..\configure.py --enable-optimize
  - C:\Python27\Scripts\ambuild

after_build:
  - if /i "%APPVEYOR_REPO_TAG%"=="true" 7z a sm-ripext-%APPVEYOR_REPO_TAG_NAME%-windows.zip .\package\*

artifacts:
  - path: build\sm-ripext-$(appveyor_repo_tag_name)-windows.zip

deploy:
  - provider: GitHub
    auth_token:
      secure: OWd5i64Jk8mOm7arzGh1lZMp7qWM4/x1vrekDhEvXlVAk1yus5BBeoKH8QkI9Yv9
    artifact: build\sm-ripext-$(appveyor_repo_tag_name)-windows.zip
    on:
      appveyor_repo_tag: true
